---
# tasks file for arillso.network

- name: "windows : {{ 'Enable' if loop_e else 'Disable' }} {{ loop_v }}"
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
    value: '{{ loop_v }}'
    datatype: dword
    data: "{{ '00000001' if loop_e else '00000000' }}"
  vars:
    loop_e: '{{ network_loop_smb_item.enable }}'
    loop_v: '{{ network_loop_smb_item.value }}'
